### ISSUE TITLE
blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#13]
[i] Target: https://raw.githubusercontent.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists/main/domlists/aiofireboggreen.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 537973 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "newntflix-popup"

  [i] List has been updated

**Comment by KnightmareVIIVIIXC** [comment]
This entry appears to come from [Dandelion Sprout's Anti Malware filter](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt) and it is labeled as a random discord server.
