### ISSUE TITLE
Blocklist fix

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#14]
[i] Target: https://raw.githubusercontent.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists/main/lists/aiofirebogbluegreen.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 719248 ABP-style domains (ignored 2 non-domain entries)
      Sample of non-domain entries:
        - "||cpng.lol.^"
        - "||mishop.pandora.xiaomi.com.^"

I think removing the ending dot( . ) in the above domains should fix the problem.

I might be totally wrong though correct me if I am.

**Comment by KnightmareVIIVIIXC** [comment]
I fixed mishop.pandora.xiaomi.com but cpng.lol is in [Adguard DNS](https://filters.adtidy.org/extension/chromium/filters/15.txt) with the period at the end.

**Comment by KnightmareVIIVIIXC** [comment]
Found more entries that end in `.^`
Should be fixed next update
