### ISSUE TITLE
Unblock Request - ||worldcoin.org^

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#15]
#### Which domain/domains need to be unblocked?

worldcoin.org

#### Which list are you using?

- [ ] 🟧 Bog
- [ ] 🟦 Blue
- [ ] 🟩 Green
- [x] 🔶 Blue/Green

#### Justification
Provide a brief explanation of why you think the specified domain(s) should be unblocked. Include any relevant context or evidence to support your request.
Worldcoin is an iris biometric cryptocurrency project developed by San Francisco- and Berlin-based Tools for Humanity. Founded in 2019 by OpenAI chief executive Sam Altman, Max Novendstern, and Alex Blania, Worldcoin is backed by venture capital firm Andreessen Horowitz.
The Worldcoin system revolves around World ID, a privacy-preserving global identity network that enables users to verify their humanness online ("Proof of Personhood") while maintaining their privacy through zero-knowledge proofs. To get a World ID, individuals must visit a physical imaging device called the Orb to get their iris scanned.
All Orb-verified World ID holders are entitled to claim recurring grants of free WLD tokens, Worldcoin's ERC-20 utility token on the Ethereum blockchain. This has the potential to make WLD the most widely distributed digital currency.
The WLD token is designed to have governance properties, empowering users by giving them a say over the future of the protocol. Beyond conventional "one-token-one-vote" governance, Worldcoin aims to enable "one-person-one-vote" mechanisms leveraging the World ID system.
Worldcoin launched out of beta in July 2023 with 11 Orb locations in the U.S. and plans for 35 cities in 20 countries. However, the currency has not formally launched in the U.S. and other countries due to regulatory concerns around privacy and potential misuse.

#### Additional Information
Add any supplementary information or details that might be useful for reviewing and processing this request.

#### Checklist
Before submitting this issue, make sure you have completed the following:

- [x] Searched for existing issues related to this domain unblocking request.
- [x] Ensured that the request aligns with the project's guidelines and policies.

#### Declaration
By submitting this request, I confirm that the information provided is accurate and that I have read and understood the project's domain unblocking policies.

- [x] Yes, I confirm

**Comment by KnightmareVIIVIIXC** [comment]
![image](https://github.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists/assets/114373431/fccd5e33-2292-4717-aa20-ca95622f8a3d)
Placeholder to fix later

**Comment by AyanokojiK1yotaka** [comment]
Worldcoin is a cryptocurrency project co-founded by Sam Altman, CEO of OpenAI, and Alex Blania. The project aims to create a globally inclusive digital currency that provides universal access to the global economy. THE same Sam altman who built CHATGPT.
i cant open my worldcoin app

**Comment by KnightmareVIIVIIXC** [comment]
Should be removed during the next update
