### ISSUE TITLE
Blocklist FIX needed

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#17]
[i] Target: https://raw.githubusercontent.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists/main/lists/aiofirebogbluegreen.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 722120 ABP-style domains (ignored 216113 non-domain entries)
      Sample of non-domain entries:
        - "||0-01x-merchandise.554217.xyz"
        - "||0-02pw.cfd"
        - "||0-0llx.12313123.xyz"
        - "||0-0lx.1231312.xyz"
        - "||0-0lxmarket.5767435.xyz"

**Comment by AyanokojiK1yotaka** [comment]
its missing the ^ mark i guess idk

**Comment by KnightmareVIIVIIXC** [comment]
That's weird because I compress all the lists individually and deduplicate. It's like it wasn't compressed fully.

**Comment by KnightmareVIIVIIXC** [comment]
Fixed. Don't know what happened, but fixed.
