### ISSUE TITLE
Unblock Request

### ISSUE THREAD

**Issue by malmaxx** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#18]
#### Which domains need to be unblocked?
jnn-pa.googleapis.com

#### Which list are you using?
- [ ] 🟧 Bog
- [x] 🟦 Blue
- [ ] 🟩 Green
- [ ] 🔶 Blue/Green

#### Justification
YouTube live streams crash after playing for several seconds.  Whitelisting this FQDN solves the issue.

#### Additional Information
I came across this Reddit that led me to the aforementioned solution:

https://www.reddit.com/r/firefox/comments/1ef2yo7/youtube_videos_stopping_to_play_after_a_few/

#### Checklist
Before submitting this issue, make sure you have completed the following:
- [X ] Searched for existing issues related to this domain unblocking request.
- [ X] Ensured that the request aligns with the project's guidelines and policies.

#### Declaration
By submitting this request, I confirm that the information provided is accurate and that I have read and understood the project's domain unblocking policies.
- [ X] Yes, I confirm

**Comment by KnightmareVIIVIIXC** [comment]
Should be removed next update
