### ISSUE TITLE
Unblock Request  cn.bing.com^

### ISSUE THREAD

**Issue by xiulou23** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#19]
#### Which domains need to be unblocked?
cn.bing.com

#### Which list are you using?
- [ √] 🟧 Bog
- [ ] 🟦 Blue
- [ ] 🟩 Green
- [ ] 🔶 Blue/Green

#### Justification

||cn.bing.com^ This rule prevents me from using the Bing search engine. Whatever I searched, the Bing search engine couldn't find it. When I add  @@cn.bing.com^, Bing search can be used normally. The list of rules I use is: https://raw.githubusercontent.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists/main/lists/aiofirebog.txt

#### Checklist
Before submitting this issue, make sure you have completed the following:
- [ √] Searched for existing issues related to this domain unblocking request.
- [ √] Ensured that the request aligns with the project's guidelines and policies.

#### Declaration
By submitting this request, I confirm that the information provided is accurate and that I have read and understood the project's domain unblocking policies.
- [ √] Yes, I confirm

**Comment by KnightmareVIIVIIXC** [comment]
Fixed
