### ISSUE TITLE
The Bog All-In-One (AIO) list makes Bing search and Baidu search useless

### ISSUE THREAD

**Issue by xiulou23** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#2]
I use The Bog All-In-One (AIO) list。Then I found out that this list makes Bing search and Baidu search useless. These two search engines were injured by mistake。So I want you to remove this  ||bing.*^ rule and ||shifen.com^ rule。Or add on @@||m.baidu.com^ and @@||cn.bing.com^

**Comment by KnightmareVIIVIIXC** [comment]
- The mentioned rules have been added to the exclusion list
- Tested in the background and the exclusion rules are working correctly to remove the blocked rules

**Comment by xiulou23** [comment]
> - The mentioned rules have been added to the exclusion list
> - Tested in the background and the exclusion rules are working correctly to remove the blocked rules

Bing search is still not available, and Baidu search can be used. bing search cannot be used because of this rule ||a-0001.a-msedge.net^   So I suggest we get rid of this rule
