### ISSUE TITLE
The Bog ALL-In-one list make Bing Search useless

### ISSUE THREAD

**Issue by xiulou23** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#3]
||a-0001.a-msedge.net^ This is the rule that makes Bing Search unusable。I suggest removing this rule

**Comment by KnightmareVIIVIIXC** [comment]
Pushing update now that will hopefully resolve the issue

**Comment by xiulou23** [comment]
> Update pushed. Please try again.

it is ok

**Comment by xiulou23** [comment]
> Update pushed. Please try again.

I can now use Bing Search
