### ISSUE TITLE
Your rules blocked the website of the National Bureau of Statistics of China

### ISSUE THREAD

**Issue by xiulou23** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#5]
I suggest removing the rule ||www.ce.cn^   ,www.ce.cn  This website is not a malicious website nor an advertising domain, this is the website of China's National Bureau of Statistics, and this website will publish some economic data of China, such as the total GDP and so on

**Comment by KnightmareVIIVIIXC** [comment]
I can't find that rule in any of my lists.

**Comment by xiulou23** [comment]
> I can't find that rule in any of my lists.

![图片](https://github.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists/assets/133690386/2743a5d2-0864-440e-8d36-8a46db6b1a77)
 you can look my picture

**Comment by KnightmareVIIVIIXC** [comment]
I found it right after sending that comment but it should be fixed now:
![image](https://github.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists/assets/114373431/5d4ea6ae-88b2-46da-ad04-f569dcf34600)
