### ISSUE TITLE
Domain urbandictionary.com blocked by The Bog AIO List

### ISSUE THREAD

**Issue by QWIILXEY** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#6]
#### Domain(s) in Question

urbandictionary.com

#### List(s) in Question

- [X] 🟧 Bog
- [X] 🟦 Blue
- [ ] 🟩 Green
- [X] 🔶 Blue/Green

#### Justification
urban dictionary is a crowdsourced dictionary for things like slang words or phrases

#### Checklist
Before submitting this issue, make sure you have completed the following:

- [x] Searched for existing issues related to this domain unblocking request.
- [x] Ensured that the request aligns with the project's guidelines and policies.

#### Declaration
By submitting this request, I confirm that the information provided is accurate and that I have read and understood the project's domain unblocking policies.

- [x] Yes, I confirm

**Comment by KnightmareVIIVIIXC** [comment]
I'm on it

**Comment by KnightmareVIIVIIXC** [comment]
Thank you for the feedback
