### ISSUE TITLE
Domains deviantart.com and giphy.com blocked by [List Name]

### ISSUE THREAD

**Issue by QWIILXEY** [KnightmareVIIVIIXC/AIO-Firebog-Blocklists#7]
#### Domain(s) in Question
deviantart.com
giphy.com

#### List(s) in Question

- [x] 🟧 Bog
- [ ] 🟦 Blue
- [ ] 🟩 Green
- [ ] 🔶 Blue/Green

#### Justification
Deviantart is a website that allows users to upload and view artwork
Giphy is a website that allows users to view and upload gifs

#### Checklist
Before submitting this issue, make sure you have completed the following:

- [x] Searched for existing issues related to this domain unblocking request.
- [x] Ensured that the request aligns with the project's guidelines and policies.

#### Declaration
By submitting this request, I confirm that the information provided is accurate and that I have read and understood the project's domain unblocking policies.

- [x] Yes, I confirm

**Comment by KnightmareVIIVIIXC** [comment]
Will be fixed next update

**Comment by KnightmareVIIVIIXC** [comment]
It is done
